package enums;

public enum GameOption {
    LEADER_SKILLS,
    STRONGHOLD_SKILLS,
    TECH_TOKENS,
    ALTERNATE_SPICE_PRODUCTION,
    SANDTROUT,
    EXPANSION_TREACHERY_CARDS,
    CHEAP_HERO_TRAITOR,
    HARKONNEN_MULLIGAN,
    FREMEN_TRIGGER_ALTERNATE_SPICE_PRODUCTION,
    FAMILY_ATOMICS_TO_DISCARD
}
