package enums;

public enum GameOption {
    HOMEWORLDS,
    LEADER_SKILLS,
    STRONGHOLD_SKILLS,
    TECH_TOKENS,
    ALTERNATE_SPICE_PRODUCTION,
    SANDTROUT,
    EXPANSION_TREACHERY_CARDS,
    CHEAP_HERO_TRAITOR,
    HARKONNEN_MULLIGAN,
    FREMEN_TRIGGER_ALTERNATE_SPICE_PRODUCTION,
    FAMILY_ATOMICS_TO_DISCARD,
    REPLACE_SHAI_HULUD_WITH_MAKER,
    EM_EXPANSION_TREACHERY_CARDS,
    TREACHERY_CARD_COUNT_PUBLIC,
    SPICE_PUBLIC,
    IX_ONLY_1_CARD_PER_FACTION,
}
