package enums;

public enum MoveType {
    SHIPMENT,
    MOVEMENT,
    STARTING_FORCES,
    BT_HT,
    FREMEN_AMBASSADOR,
    GUILD_AMBASSADOR,
    FREMEN_RIDE,
    SHAI_HULUD_PLACEMENT,
    GREAT_MAKER_PLACEMENT,
    HMS_PLACEMENT,
    ENTER_DISCOVERY_TOKEN,
    TBD,
}
