package enums;

public enum SetupStep {
    HOMEBREW_LEADERS,
    CREATE_DECKS,
    FACTION_POSITIONS,
    BG_PREDICTION,
    FREMEN_FORCES,
    BG_FORCE,
    MORITANI_FORCE,
    IX_CARD_SELECTION,
    TREACHERY_CARDS,
    LEADER_SKILL_CARDS,
    SHOW_LEADER_SKILLS,
    ECAZ_LOYALTY,
    HARKONNEN_TRAITORS,
    TRAITORS,
    BT_FACE_DANCERS,
    STORM_SELECTION,
    IX_HMS_PLACEMENT,
    START_GAME,
}
