on:
  pull_request:
    branches: [ "master" ]
#    types:
#      - closed

permissions:
  pull-requests: read
  contents: read

jobs:
  message:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: kceb/pull-request-url-action@v1
        id: pr-url
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Pull request merged: ${{ github.event.pull_request.title }}\nBy ${{ github.event.pull_request.user.login }}\nSee ${{ steps.pr-url.outputs.url }} for details."